# Generated by Django 3.2.7 on 2021-10-16 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_assessment', models.BooleanField(default=True)),
                ('incident_response', models.BooleanField(default=True)),
                ('cyber_crime_investigation', models.BooleanField(default=True)),
                ('open_source_intelligence', models.BooleanField(default=True)),
                ('hack_recovery', models.BooleanField(default=True)),
                ('virus_removal', models.BooleanField(default=True)),
                ('digital_forensic', models.BooleanField(default=True)),
                ('digital_integration', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
