# Generated by Django 3.2.7 on 2021-10-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='admin_type',
            field=models.CharField(choices=[('bcs_admin', 'BCS Admin'), ('pcs_admin', 'PCS Admin'), ('academy_admin', 'Academy Admin'), ('blog_admin', 'Blog Admin')], max_length=264),
        ),
    ]
