# Generated by Django 3.2.7 on 2021-11-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bcs_head',
            field=models.BooleanField(default=False, help_text='Designate if the user is BCS Admin', verbose_name='BCS Admin Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blogger',
            field=models.BooleanField(default=False, help_text='Designate if the user is Blog Admin ', verbose_name='Blog Admin Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pcs_head',
            field=models.BooleanField(default=False, help_text='Designate if the user is PCS Admin', verbose_name='PCS Admin Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sales',
            field=models.BooleanField(default=False, help_text='Designate if the user is sales', verbose_name='Sales Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sales_head',
            field=models.BooleanField(default=False, help_text='Designate if the user is sales head ', verbose_name='Sales Head Status'),
        ),
    ]
