# Generated by Django 3.2.7 on 2021-11-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20211103_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='users/'),
        ),
    ]
