# Generated by Django 3.2.7 on 2021-10-02 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Joined'),
            preserve_default=False,
        ),
    ]
