# Generated by Django 3.2.7 on 2021-10-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_user_date_joied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joied',
            new_name='date_joined',
        ),
    ]
