# Generated by Django 3.2.7 on 2021-10-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_rename_date_joied_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False, help_text='Receive Email About Update and Notifications', verbose_name='Newsletter'),
        ),
    ]
