# Generated by Django 3.2.7 on 2021-10-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_user_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Verify User Email Address', verbose_name='Email Verified'),
        ),
    ]
