# Generated by Django 3.2.7 on 2021-10-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_user_email_verified'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
