# Generated by Django 3.2.7 on 2021-10-09 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.ImageField(upload_to='service_icon/', verbose_name='Service Icon')),
                ('service_title', models.CharField(max_length=264, verbose_name='Service Title')),
                ('short_description', models.TextField(max_length=1000, verbose_name='Short Description')),
                ('service_header', tinymce.models.HTMLField(verbose_name='Service Header')),
                ('service_body', tinymce.models.HTMLField(verbose_name='Service Body')),
                ('service_footer', tinymce.models.HTMLField(verbose_name='Service Footer')),
                ('has_sub_service', models.BooleanField(default=False, verbose_name='Has Sub Services')),
                ('is_subscription_based', models.BooleanField(default=False, verbose_name='Is Subscription Based')),
                ('total_customer', models.IntegerField(verbose_name='Total Customer')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=264, verbose_name='Category Name')),
                ('category_description', models.TextField(max_length=1000, verbose_name='Category Description')),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBasedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=264, verbose_name='Package Name')),
                ('servers', models.IntegerField()),
                ('websites', models.IntegerField()),
                ('workstations', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessSecurity.service')),
            ],
            options={
                'verbose_name_plural': 'Subscription Based Packages',
            },
        ),
        migrations.CreateModel(
            name='UserAllowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_service', to='BusinessSecurity.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users Allowed',
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('total_customer', models.IntegerField(verbose_name='Total Customer')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservice_service', to='BusinessSecurity.service')),
            ],
            options={
                'verbose_name_plural': 'Sub Services',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=264, verbose_name='Feature Name')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_subscription', to='BusinessSecurity.subscriptionbasedpackage')),
            ],
            options={
                'verbose_name_plural': 'Package Features',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='BusinessSecurity.servicecategory'),
        ),
    ]
