# Generated by Django 3.2.7 on 2021-10-25 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_type', models.CharField(choices=[('software_companies', 'Software Companies'), ('government_agencies', 'Government Agencies'), ('law_enforcement', 'Law Enforcement'), ('financial_institutes', 'Financial Institutes'), ('telecommunication_companies', 'Telecommunication Companies'), ('wealth_management', 'Wealth Management'), ('educational_institutes', 'Educational Institute'), ('isp_companies', 'ISP Companies'), ('ecommerce_business', 'Ecommerce Business'), ('law_farm', 'Law Farm'), ('small_and_medium_business', 'Small and Medium Business'), ('health_care_institutes', 'Health Care Institutes')], max_length=264)),
                ('company_name', models.CharField(max_length=264)),
                ('company_logo', models.ImageField(upload_to='company/')),
                ('website', models.URLField(default='https://', max_length=264)),
                ('business_size', models.IntegerField(default=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=264)),
                ('medium', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=264)),
                ('speaker', models.CharField(max_length=264)),
                ('category', models.CharField(choices=[('for_business_security', 'For Business CyberSecurity'), ('for_personal_security', 'For Personal CyberSecurity')], max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('date_field', models.DateField()),
                ('time_field', models.TimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=264)),
                ('event_description', tinymce.models.HTMLField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='InputFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('file', 'file')], max_length=264)),
                ('placeholder', models.CharField(blank=True, max_length=264, null=True)),
            ],
            options={
                'verbose_name_plural': 'Input Fields',
            },
        ),
        migrations.CreateModel(
            name='NewsSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.ImageField(upload_to='service_icon/', verbose_name='Service Icon')),
                ('service_title', models.CharField(max_length=264, verbose_name='Service Title')),
                ('short_description', models.TextField(max_length=1000, verbose_name='Short Description')),
                ('service_header', tinymce.models.HTMLField(blank=True, verbose_name='Service Header')),
                ('service_body', tinymce.models.HTMLField(blank=True, verbose_name='Service Body')),
                ('service_footer', tinymce.models.HTMLField(blank=True, verbose_name='Service Footer')),
                ('has_sub_service', models.BooleanField(default=False, verbose_name='Has Sub Services')),
                ('is_subscription_based', models.BooleanField(default=False, verbose_name='Is Subscription Based')),
                ('total_customer', models.IntegerField(blank=True, default=0, verbose_name='Total Customer')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=264, verbose_name='Category Name')),
                ('category_description', models.TextField(max_length=1000, verbose_name='Category Description')),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBasedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=264, verbose_name='Package Name')),
                ('servers', models.IntegerField()),
                ('websites', models.IntegerField()),
                ('workstations', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('duration_type', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=264)),
                ('price', models.IntegerField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessSecurity.service')),
            ],
            options={
                'verbose_name_plural': 'Subscription Based Packages',
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('total_customer', models.IntegerField(blank=True, default=0, verbose_name='Total Customer')),
            ],
            options={
                'verbose_name_plural': 'Sub Services',
            },
        ),
        migrations.CreateModel(
            name='UsersBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=264)),
                ('privilege', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], max_length=264)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_business', to='BusinessSecurity.business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Businesses',
            },
        ),
        migrations.CreateModel(
            name='UserAllowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_service', to='BusinessSecurity.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users Allowed',
            },
        ),
        migrations.CreateModel(
            name='SubServiceInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.CharField(blank=True, max_length=264, null=True)),
                ('inputfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subserviceinput_inputfield', to='BusinessSecurity.inputfields')),
                ('subservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subserviceinput_subservice', to='BusinessSecurity.subservice')),
            ],
            options={
                'db_table': 'BusinessSecurity_subservice_inputfields',
            },
        ),
        migrations.AddField(
            model_name='subservice',
            name='fields',
            field=models.ManyToManyField(related_name='subservice_inputfields', through='BusinessSecurity.SubServiceInput', to='BusinessSecurity.InputFields'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservice_service', to='BusinessSecurity.service'),
        ),
        migrations.CreateModel(
            name='SubscriptionFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=264, verbose_name='Feature Name')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_subscription', to='BusinessSecurity.subscriptionbasedpackage')),
            ],
            options={
                'verbose_name_plural': 'Package Features',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='BusinessSecurity.servicecategory'),
        ),
        migrations.CreateModel(
            name='RegisteredEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_event_event', to='BusinessSecurity.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_event_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Registered Events',
            },
        ),
    ]
