# Generated by Django 3.2.7 on 2021-10-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='fields',
        ),
        migrations.AddField(
            model_name='inputfields',
            name='name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
