# Generated by Django 3.2.7 on 2021-10-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='total_customer',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total Customer'),
        ),
    ]
