# Generated by Django 3.2.7 on 2021-12-21 09:31

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_choice', models.CharField(choices=[('bcs', 'BCS'), ('pcs', 'PCS')], max_length=255)),
                ('service_icon', models.ImageField(upload_to='service_icon/', verbose_name='Service Icon')),
                ('service_title', models.CharField(max_length=264, verbose_name='Service Title')),
                ('short_description', models.TextField(max_length=1000, verbose_name='Short Description')),
                ('service_header', tinymce.models.HTMLField(blank=True, verbose_name='Service Header')),
                ('service_body', tinymce.models.HTMLField(blank=True, verbose_name='Service Body')),
                ('service_footer', tinymce.models.HTMLField(blank=True, verbose_name='Service Footer')),
                ('total_customer', models.IntegerField(blank=True, default=0, verbose_name='Total Customer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_service_category', to='BusinessSecurity.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Subscription Services',
            },
        ),
    ]
