# Generated by Django 3.2.7 on 2021-10-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subserviceinput',
            name='input_value',
        ),
    ]
