# Generated by Django 3.2.7 on 2021-10-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionbasedpackage',
            name='duration_type',
            field=models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=264),
        ),
    ]
