# Generated by Django 3.2.7 on 2021-10-18 11:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0002_auto_20211018_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=264)),
                ('medium', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=264)),
                ('speaker', models.CharField(max_length=264)),
                ('category', models.CharField(choices=[('for_business_security', 'For Business CyberSecurity'), ('for_personal_security', 'For Personal CyberSecurity')], max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('date_field', models.DateField()),
                ('time_field', models.TimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'completed'), ('canceled', 'canceled')], max_length=264)),
                ('event_description', tinymce.models.HTMLField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
