# Generated by Django 3.2.7 on 2021-10-10 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusinessSecurity', '0002_business_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbusiness',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_business', to='BusinessSecurity.business'),
        ),
        migrations.AlterField(
            model_name='usersbusiness',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
