# Generated by Django 3.2.7 on 2021-10-27 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusinessSecurity', '0002_remove_subserviceinput_input_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubserviceInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputinfo', models.CharField(max_length=255)),
                ('inputfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputfield_input', to='BusinessSecurity.subserviceinput')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subservice_input', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
