# Generated by Django 3.2.7 on 2021-10-23 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0002_auto_20211023_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServiceInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.CharField(blank=True, max_length=264, null=True)),
                ('inputfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subserviceinput_inputfield', to='BusinessSecurity.inputfields')),
                ('subservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subserviceinput_subservice', to='BusinessSecurity.subservice')),
            ],
            options={
                'db_table': 'BusinessSecurity_subservice_inputfields',
            },
        ),
        migrations.AddField(
            model_name='subservice',
            name='fields',
            field=models.ManyToManyField(related_name='subservice_inputfields', through='BusinessSecurity.SubServiceInput', to='BusinessSecurity.InputFields'),
        ),
    ]
