# Generated by Django 3.2.7 on 2021-10-09 09:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0002_alter_service_total_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_body',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Service Body'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_footer',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Service Footer'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_header',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Service Header'),
        ),
    ]
