# Generated by Django 3.2.7 on 2021-12-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0002_subscriptionservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionfeatures',
            name='feature',
            field=models.CharField(default='test', max_length=264, verbose_name='Feature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionbasedpackage',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessSecurity.subscriptionservices'),
        ),
    ]
