# Generated by Django 3.2.7 on 2021-10-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0003_auto_20211023_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfields',
            name='name',
        ),
    ]
