# Generated by Django 3.2.7 on 2021-10-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0003_auto_20211009_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='total_customer',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total Customer'),
        ),
    ]
