# Generated by Django 3.2.7 on 2021-10-20 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusinessSecurity', '0003_auto_20211018_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_event_event', to='BusinessSecurity.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_event_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
