# Generated by Django 3.2.7 on 2021-12-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0003_auto_20211221_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionbasedpackage',
            name='servers',
        ),
        migrations.RemoveField(
            model_name='subscriptionbasedpackage',
            name='websites',
        ),
        migrations.RemoveField(
            model_name='subscriptionbasedpackage',
            name='workstations',
        ),
    ]
