# Generated by Django 3.2.7 on 2021-10-10 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0003_auto_20211010_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('f672ff7f-e5fc-4d6d-a3c3-2670089bfe52'), max_length=264, unique=True),
        ),
    ]
