# Generated by Django 3.2.7 on 2021-10-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0004_registeredevents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredevents',
            options={'verbose_name_plural': 'Registered Events'},
        ),
    ]
