# Generated by Django 3.2.7 on 2021-11-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_service', to='BusinessSecurity.service'),
            preserve_default=False,
        ),
    ]
