# Generated by Django 3.2.7 on 2021-10-09 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusinessSecurity', '0004_alter_subservice_total_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_type', models.CharField(choices=[('software_companies', 'Software Companies'), ('government_agencies', 'Government Agencies'), ('law_enforcement', 'Law Enforcement'), ('financial_institutes', 'Financial Institutes'), ('telecommunication_companies', 'Telecommunication Companies'), ('wealth_management', 'Wealth Management'), ('educational_institutes', 'Educational Institute'), ('isp_companies', 'ISP Companies'), ('ecommerce_business', 'Ecommerce Business'), ('law_farm', 'Law Farm'), ('small_and_medium_business', 'Small and Medium Business'), ('health_care_institutes', 'Health Care Institutes')], max_length=264)),
                ('company_name', models.CharField(max_length=264)),
                ('website', models.CharField(max_length=264)),
                ('business_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=264)),
                ('privilege', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], max_length=264)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_business', to='BusinessSecurity.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
