# Generated by Django 3.2.7 on 2021-10-10 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0005_alter_business_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
