# Generated by Django 3.2.7 on 2021-11-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0009_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('attending', 'Attending'), ('on_progress', 'On Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='new', max_length=250),
        ),
    ]
