# Generated by Django 3.2.7 on 2021-11-09 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusinessSecurity', '0016_auto_20211109_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersbusiness',
            name='user',
        ),
        migrations.AddField(
            model_name='usersbusiness',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to='Account.user'),
            preserve_default=False,
        ),
    ]
