# Generated by Django 3.2.7 on 2021-11-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0017_auto_20211109_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbusiness',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_business', to='BusinessSecurity.business'),
        ),
    ]
