# Generated by Django 3.2.7 on 2021-11-09 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0018_alter_usersbusiness_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersbusiness',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
