# Generated by Django 3.2.7 on 2021-11-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessSecurity', '0019_usersbusiness_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='has_sub_service',
            field=models.BooleanField(default=True, verbose_name='Has Sub Services'),
        ),
    ]
