# Generated by Django 3.2.7 on 2021-12-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blogsubscription_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogSubscription',
        ),
    ]
