# Generated by Django 3.2.7 on 2021-10-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_sub_category', to='Blog.blogsubcategory'),
        ),
    ]
