# Generated by Django 3.2.7 on 2021-10-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_post_sub_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=80)),
                ('sub_category', models.ManyToManyField(blank=True, null=True, related_name='filter_subcategory', to='Blog.BlogSubCategory')),
            ],
            options={
                'verbose_name_plural': 'Blog Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='filter_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_filter', to='Blog.filteroption'),
        ),
    ]
