# Generated by Django 3.2.7 on 2021-10-03 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.DurationField(default=datetime.timedelta(seconds=180)),
        ),
    ]
