# Generated by Django 3.2.7 on 2021-10-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='shot_description',
            new_name='short_description',
        ),
    ]
