# Generated by Django 3.2.7 on 2021-10-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20211006_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filteroption',
            options={'verbose_name_plural': 'Blog Filter Option'},
        ),
    ]
