# Generated by Django 3.2.7 on 2021-10-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20211006_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
