# Generated by Django 3.2.7 on 2021-10-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20211007_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_view',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
