# Generated by Django 3.2.7 on 2021-10-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_post_total_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total_view',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
