# Generated by Django 3.2.7 on 2021-10-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_tags_options'),
        ('Blog', '0012_alter_post_total_view'),
    ]

    operations = [
    ]
