# Generated by Django 3.2.7 on 2021-10-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_merge_20211007_1709'),
        ('Blog', '0013_merge_20211009_1049'),
    ]

    operations = [
    ]
