# Generated by Django 3.2.7 on 2021-10-16 08:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=264)),
                ('duration', models.CharField(choices=[('one_month', 'One Month'), ('two_months', 'Two Months'), ('three_months', 'Three Months'), ('six_months', 'Six Months'), ('one_year', 'One Year')], max_length=264)),
                ('short_description', models.TextField(max_length=1000)),
                ('long_description', tinymce.models.HTMLField(max_length=5000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
