# Generated by Django 3.2.7 on 2021-12-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('Business', 'Business'), ('Personal', 'Personal')], max_length=264)),
                ('category_name', models.CharField(max_length=264)),
            ],
        ),
    ]
