# Generated by Django 3.2.7 on 2021-10-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=264)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_course', to='Academy.course')),
            ],
        ),
    ]
