# Generated by Django 3.2.7 on 2021-10-17 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=264)),
                ('text_instruction', models.TextField(max_length=5000)),
                ('course_video', models.FileField(upload_to='course/<django.db.models.fields.related.ForeignKey>/')),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='course/<django.db.models.fields.related.ForeignKey>/')),
                ('resource_file', models.FileField(upload_to='course/<django.db.models.fields.related.ForeignKey>/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_section', to='Academy.section')),
            ],
        ),
    ]
