# Generated by Django 3.2.7 on 2021-12-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0002_coursecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_coursecategory', to='Academy.coursecategory'),
            preserve_default=False,
        ),
    ]
