# Generated by Django 3.2.7 on 2021-12-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0003_course_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_category',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
