# Generated by Django 3.2.7 on 2021-12-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0004_auto_20211228_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
