# Generated by Django 3.2.7 on 2021-10-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0004_alter_content_text_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='course_video',
            field=models.FileField(upload_to='course/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='course/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='resource_file',
            field=models.FileField(upload_to='course/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_instruction',
            field=models.FileField(upload_to='course/'),
        ),
    ]
